server:
  port: 8085

mybatis:
  typeAliasesPackage: com.sisp.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myweb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1520229462
    driver-class-name: com.mysql.cj.jdbc.Driver

